name: security-Quality scanning.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  secret-scan:
    name: Secret Scan with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    #needs: secret-scan
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  # Modify as per your codebase

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    #needs: sonarqube

    steps:
      - name: Trivy scan - Filesystem
        uses: aquasecurity/trivy-action@master
        with:
         scan-type: 'fs'
         scan-ref: '.'  

  notify:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set status message
        id: set-status
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "SUBJECT=✅ Build Success" >> $GITHUB_ENV
          else
            echo "SUBJECT=❌ Build Failed" >> $GITHUB_ENV
          fi

      - name: Send Outlook Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ env.SUBJECT }}
          to: kanagarasu.s@sq1.security
          from: GitHub CI <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,

            Your GitHub Actions workflow has completed.

            • Status: ${{ job.status }}

